# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: YoJJeremiah.github.io
title: Flux Mod
email: N/A
author: Jeremiah H.
description: > # "Welcome to FluxMod, your all-in-one service provider dedicated to propelling your community to new heights! With a suite of diverse services, our Discord bot takes the lead in fostering growth and engagement. From community management to dynamic features, FluxMod is your catalyst for success. Let us amplify your online presence, connect with your audience, and watch your community flourish like never before. Elevate, engage, and evolve with FluxMod – where limitless possibilities meet seamless service!
copyright: 'Copyright &copy; 2024 FluxMod. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: N/A
  - title: github
    url: https://github.com/YoJJeremiah
  - title: linkedin
    url: N/A
